import { useStore } from "../store";
import Topbar from "../components/Topbar";
import MerchantLogo from "../components/MerchantLogo";

export default function Report() {
  const { data } = useStore();
  const { summary, subscriptions, profile } = data;
  const actionable = subscriptions.filter((s) => s.save > 0);

  return (
    <>
      <div className="noprint">
        <Topbar k="Shareable" title="Leak Report" />
        <button className="btn btn-grad" style={{ marginBottom: 20 }} onClick={() => window.print()}>🖨️ Save as PDF / Print</button>
      </div>

      <div className="report">
        <div className="report-head">
          <div className="brand"><div className="mark" style={{ width: 34, height: 34, borderRadius: 10, display: "grid", placeItems: "center", background: "var(--grad)", fontSize: 18 }}>🧟</div><b>Zombii</b></div>
          <div className="report-date">{new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}</div>
        </div>

        <h1 className="report-title">Subscription Leak Report</h1>
        <p className="report-lead">Prepared for {profile.name} · scanned {summary.scannedTxns} transactions</p>

        <div className="report-hero">
          <div><div className="rl">Leaking / year</div><div className="rn">₹{summary.totalLeak.toLocaleString("en-IN")}</div></div>
          <div><div className="rl">Subscriptions</div><div className="rn">{summary.count}</div></div>
          <div><div className="rl">Zombies</div><div className="rn">{summary.zombies}</div></div>
          <div><div className="rl">Leak score</div><div className="rn">{summary.overallScore}/100</div></div>
        </div>

        <h3 className="report-h">Action plan</h3>
        <table className="report-table">
          <thead><tr><th>Subscription</th><th>Monthly</th><th>Issue</th><th>Action</th><th>Saves/yr</th></tr></thead>
          <tbody>
            {actionable.map((s) => (
              <tr key={s.name}>
                <td>{s.name}</td>
                <td>₹{s.price.toLocaleString("en-IN")}</td>
                <td>{s.flag.txt}</td>
                <td>{s.action === "cancel" ? "Cancel" : "Downgrade / renegotiate"}</td>
                <td>₹{s.save.toLocaleString("en-IN")}</td>
              </tr>
            ))}
          </tbody>
        </table>

        {summary.overlaps?.length > 0 && (
          <>
            <h3 className="report-h">Overlapping services</h3>
            <ul className="report-ul">
              {summary.overlaps.map((o) => (
                <li key={o.category}>{o.category}: {o.count} services — consolidate to save ₹{o.annualWaste.toLocaleString("en-IN")}/yr</li>
              ))}
            </ul>
          </>
        )}

        <div className="report-foot">Generated by Zombii · your statement was analysed on-demand and never stored.</div>
      </div>
    </>
  );
}
